# Generated by Django 5.1 on 2024-08-26 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_fee', models.FloatField()),
                ('payment_status', models.CharField(default='Pending', max_length=20)),
                ('encounter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='encounters.encounter')),
            ],
        ),
    ]
