# Generated by Django 5.1 on 2024-08-26 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_alter_appointment_doctor_alter_appointment_patient_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='encounter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='encounters.encounter'),
        ),
    ]
