# Generated by Django 5.1 on 2024-08-29 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_remove_doctor_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.customuser'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='customuser_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.customuser'),
        ),
    ]
