# Generated by Django 5.1 on 2024-08-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
