# Generated by Django 5.1 on 2024-08-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_module_perms',
        ),
    ]
