# Generated by Django 5.1 on 2024-09-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Patient', 'Patient')], default='Patient'),
            preserve_default=False,
        ),
    ]
