# Generated by Django 5.1 on 2024-08-26 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medications', models.TextField()),
                ('surgeries', models.TextField()),
                ('allergies', models.TextField()),
                ('health_conditions', models.TextField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_users.patient')),
            ],
        ),
    ]
