# Generated by Django 5.1 on 2024-08-26 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
        ('medicine', '0001_initial'),
        ('users', '0002_doctor_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='encounters.appointment'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='prescription',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine'),
        ),
    ]
