# Generated by Django 5.1 on 2024-09-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0003_alter_appointment_status'),
        ('users', '0011_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('doctor', 'patient', 'appointment_datetime')},
        ),
    ]
