# Generated by Django 5.1 on 2024-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('formula', models.TextField(unique=True)),
            ],
        ),
    ]
