# Generated by Django 5.1 on 2024-08-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('designation', models.CharField(max_length=255)),
                ('speciality', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('blood_group', models.CharField(max_length=3)),
                ('disease_stage', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
